# Generated by Django 5.2.16 on 2026-09-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_contactsubmission_contactmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline for the popup modal', max_length=200)),
                ('badge_text', models.CharField(blank=True, help_text='Top badge label (e.g. 🎁 SPECIAL OFFER, 📞 VIP CONSULTATION)', max_length=100, null=True)),
                ('popup_type', models.CharField(choices=[('OFFER', 'Special Offer 🎁'), ('CALL_BOOKING', 'Book a Call for Saree Selection 📞'), ('VIDEO', 'Saree Video 🎥'), ('WHATSAPP', 'WhatsApp / Enquiry 💬'), ('COLLECTION', 'Collection Promotion 🛍️')], default='OFFER', help_text='Select the interactive behavior and layout for this popup', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Detailed message, terms, or promotional offer details', null=True)),
                ('image', models.ImageField(blank=True, help_text='Visual image banner for the popup', null=True, upload_to='popups/')),
                ('video', models.FileField(blank=True, help_text='Upload optional MP4/WebM video', null=True, upload_to='popups/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Optional external or Cloudinary video URL', null=True)),
                ('cta_text', models.CharField(default='Explore Now', help_text='Button label (e.g. Shop Collection, Book My Call)', max_length=60)),
                ('cta_link', models.CharField(default='/shop/', help_text='Destination URL when visitor clicks the CTA button', max_length=255)),
                ('coupon_code', models.CharField(blank=True, help_text='Optional discount code to display with 1-click copy', max_length=50, null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Custom WhatsApp number (leave blank to use store default)', max_length=20, null=True)),
                ('whatsapp_message', models.CharField(blank=True, default='Hello Rangam Saradha Silks, I would like to know more about your authentic handloom sarees.', help_text='Pre-filled WhatsApp message', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this popup from appearing on the website')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority. If multiple active popups exist, only the highest priority popup is shown.')),
                ('start_date', models.DateTimeField(blank=True, help_text='Popup starts appearing after this date/time (leave blank for immediately)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Popup stops appearing after this date/time (leave blank for no expiration)', null=True)),
                ('show_delay_seconds', models.PositiveIntegerField(default=2, help_text='Delay in seconds after page load before displaying (1-2s recommended)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup',
                'verbose_name_plural': 'Popups',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
