# Generated by Django 5.2.16 on 2026-09-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='description',
            field=models.TextField(blank=True, default='Pure Silks. Timeless Traditions. For Your Most Precious Moments.', help_text='Supporting description below headline', null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='heritage_badge_1',
            field=models.CharField(blank=True, default='Authentic Handloom', max_length=60),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='heritage_badge_2',
            field=models.CharField(blank=True, default='Pure Silk Guaranteed', max_length=60),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='heritage_badge_3',
            field=models.CharField(blank=True, default='A Legacy of Tradition', max_length=60),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='Watch Our Story', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='secondary_button_url',
            field=models.CharField(blank=True, help_text='Link for secondary button (leave blank to open Story Video modal)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional background video file (.mp4, .webm)', null=True, upload_to='slider_videos/'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional background video URL (e.g. Cloudinary or direct MP4 link)', null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='button_text',
            field=models.CharField(default='Explore Collections', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(help_text='Background image (used if no video is provided or as poster)', upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional mobile-optimized image', null=True, upload_to='slider_mobile/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='subtitle',
            field=models.CharField(blank=True, default='HANDWOVEN HERITAGE', help_text='Eyebrow text above headline', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(default='Woven by Hand.\nMade to Treasure.', help_text='Main heading (can use line breaks)', max_length=150),
        ),
    ]
