# Generated by Django 5.2.16 on 2026-09-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_heroslider_description_heroslider_heritage_badge_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='category_button_text',
            field=models.CharField(default='View All Categories', help_text='Text for the Categories CTA button.', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='category_button_url',
            field=models.CharField(default='/shop/', help_text='URL / link for the Categories CTA button.', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='category_description',
            field=models.CharField(default='Explore timeless weaves crafted for every occasion.', help_text='Description text below Categories heading.', max_length=255),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='category_subtitle',
            field=models.CharField(default='SHOP BY CATEGORY', help_text='Label above Categories heading.', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='category_title',
            field=models.CharField(default='Traditional Saree Collections', help_text='Main heading for the Categories section.', max_length=150),
        ),
    ]
