# Generated by Django 5.2.16 on 2026-09-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_websitesetting_category_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='cod_charge',
            field=models.DecimalField(decimal_places=2, default=49.0, help_text='Cash On Delivery fee for orders below the threshold', max_digits=10),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='cod_max_limit',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Orders at or above this amount cannot use Cash On Delivery (COD)', max_digits=10),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='gst_number',
            field=models.CharField(blank=True, default='33AAAAA0000A1Z5', help_text='Business GSTIN for invoices and tax compliance', max_length=30),
        ),
    ]
