# Generated by Django 5.2.16 on 2026-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_websitesetting_cod_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='call_booking_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Fee required to book a live video saree consultation (default: ₹50.00)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='cod_max_limit',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Orders at or above this amount receive FREE Cash On Delivery (₹0 COD fee)', max_digits=10),
        ),
    ]
