# Generated by Django 5.2.16 on 2026-09-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_websitesetting_call_booking_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='launch_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 25, 5, 0, tzinfo=datetime.timezone.utc), help_text='Exact launch date & time (Asia/Kolkata). The site automatically unlocks when this time arrives.'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='launch_mode_active',
            field=models.BooleanField(default=True, help_text='Enable Opening Soon launch lock. When active, normal visitors see the Opening Soon page until the launch datetime. Staff/Superusers can always access the site.'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='launch_tagline_1',
            field=models.CharField(default='Something Beautiful Is About to Begin', help_text='Top tagline on the Opening Soon screen', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='launch_tagline_2',
            field=models.CharField(default='Tradition in Every Weave.', help_text='Bottom tagline on the Opening Soon screen', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='launch_title',
            field=models.CharField(default='Opening Soon', help_text='Main headline on the Opening Soon screen', max_length=100),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_type',
            field=models.CharField(choices=[('OPENING_SOON', 'Opening Soon Announcement ⏳'), ('OFFER', 'Special Offer 🎁'), ('CALL_BOOKING', 'Book a Call for Saree Selection 📞'), ('VIDEO', 'Saree Video 🎥'), ('WHATSAPP', 'WhatsApp / Enquiry 💬'), ('COLLECTION', 'Collection Promotion 🛍️')], default='OFFER', help_text='Select the interactive behavior and layout for this popup', max_length=30),
        ),
    ]
