# Generated by Django 5.2.16 on 2026-09-22 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_websitesetting_launch_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popup_type',
            field=models.CharField(choices=[('OFFER', 'Special Offer 🎁'), ('CALL_BOOKING', 'Book a Call for Saree Selection 📞'), ('VIDEO', 'Saree Video 🎥'), ('WHATSAPP', 'WhatsApp / Enquiry 💬'), ('COLLECTION', 'Collection Promotion 🛍️')], default='OFFER', help_text='Select the interactive behavior and layout for this popup', max_length=30),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='bridal_banner_button_url',
            field=models.CharField(default='/shop/?category=bridal-collection', help_text='URL the button links to.', max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='launch_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 25, 5, 0, tzinfo=datetime.timezone.utc), help_text='Target launch date & time in Asia/Kolkata (e.g. 25 September 2026 at 10:30 AM). The overlay automatically disappears when this time arrives.', verbose_name='Grand Opening Date & Time (Asia/Kolkata)'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='launch_mode_active',
            field=models.BooleanField(default=True, help_text='Turn OFF anytime to immediately open the site early without touching code. When ON, normal visitors see the mandatory full-screen launch overlay until the launch date/time arrives.', verbose_name='TEMP POPUP Active (Enable/Disable)'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='launch_tagline_1',
            field=models.CharField(default='Something beautiful is about to begin.', help_text='Subtitle displayed right below the brand title.', max_length=200, verbose_name='Popup Subtitle'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='launch_tagline_2',
            field=models.CharField(default='Tradition in Every Weave', help_text='Tagline displayed below the countdown timer.', max_length=200, verbose_name='Popup Tagline'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='launch_title',
            field=models.CharField(default='Grand Opening Soon', help_text='Headline displayed on the mandatory launch overlay.', max_length=150, verbose_name='Popup Headline'),
        ),
    ]
