# Generated by Django 5.2.16 on 2026-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_update_refund_policy_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='hero_display_mode',
            field=models.CharField(choices=[('AUTO', 'Automatic (Hero Slider if active, else Offer Banner)'), ('HERO_SLIDER', 'Hero Slider Only'), ('OFFER_BANNER', 'Offer Banner Only')], default='AUTO', help_text="Choose whether to show the Hero Slider or the Offer Banner at the top of the homepage. In 'Automatic' mode, the Hero Slider is shown if active slides exist; if hero sliders are removed/deactivated, it automatically shows the Offer Banner instead. Either one will be displayed, never both simultaneously.", max_length=20, verbose_name='Homepage Top Banner Display'),
        ),
    ]
