# Generated by Django 5.2.16 on 2026-09-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_update_shipping_policy_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info & Page Settings', 'verbose_name_plural': 'Contact Info & Page Settings'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='banner_button_text',
            field=models.CharField(default='Explore Our Collection', max_length=60),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='banner_button_url',
            field=models.CharField(default='/shop/', max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='banner_description',
            field=models.TextField(default="From traditional silk sarees to elegant wedding collections, we're here to help you find the perfect saree for every occasion."),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Custom background image for the middle saree banner', null=True, upload_to='contact/'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='banner_title',
            field=models.CharField(default='Looking for the Perfect Saree?', max_length=150),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='call_btn_text',
            field=models.CharField(default='Call Now', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='call_btn_url',
            field=models.CharField(blank=True, default='tel:+919100288963', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='call_card_title',
            field=models.CharField(default='Call Us', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email_btn_text',
            field=models.CharField(default='Send Email', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email_btn_url',
            field=models.CharField(blank=True, default='mailto:rangamsaradhasilks@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email_card_title',
            field=models.CharField(default='Email Us', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_1_icon',
            field=models.CharField(default='bi-gift', help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_1_title',
            field=models.CharField(default='Wedding Collections', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_2_icon',
            field=models.CharField(default='bi-flower1', help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_2_title',
            field=models.CharField(default='Traditional Silk Sarees', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_3_icon',
            field=models.CharField(default='bi-heart', help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_3_title',
            field=models.CharField(default='Custom Orders', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_4_icon',
            field=models.CharField(default='bi-headset', help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='feature_4_title',
            field=models.CharField(default='Customer Support', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='form_button_text',
            field=models.CharField(default='Send Message', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='form_subjects',
            field=models.TextField(default='Inquiry about Pure Silk Sarees\nCustom Bridal Order\nOrder Status & Shipping\nStore Visit & Video Call\nBulk & Wholesale Inquiry\nOther Inquiries', help_text='Subject options for the form dropdown (one per line)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='form_subtitle',
            field=models.CharField(default="We'll get back to you as soon as possible.", max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='form_title',
            field=models.CharField(default='Send Us a Message', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='header_bg_image',
            field=models.ImageField(blank=True, help_text='Optional custom background/texture for the header', null=True, upload_to='contact/'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='help_description',
            field=models.TextField(default='Have a question about our pure silk sarees, custom orders, or shipping times? Drop us a line or visit our flagship store. Our team will be happy to assist you.', help_text='Introductory text explaining how customers can get in touch'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='help_eyebrow',
            field=models.CharField(default="WE'D LOVE TO HEAR FROM YOU", help_text='Small gold eyebrow label', max_length=150),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='help_title',
            field=models.CharField(default="We're Here to Help", help_text='Heading for the left contact section', max_length=150),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='hours_card_title',
            field=models.CharField(default='Working Hours', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location_button_text',
            field=models.CharField(default='Get Directions', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location_button_url',
            field=models.CharField(default='https://maps.google.com/?q=Rangam+Saradha+Silks+Dharmavaram', max_length=300),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location_description',
            field=models.TextField(default='Experience our exclusive collection in person at our Dharmavaram store.'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location_eyebrow',
            field=models.CharField(default='OUR LOCATION', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location_title',
            field=models.CharField(default='Visit Rangam Saradha Silks', max_length=150),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='page_subtitle',
            field=models.CharField(default='Connect with Rangam Saradha Silks', help_text='Subtitle under main heading', max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='page_title',
            field=models.CharField(default='Contact Us', help_text='Main heading on the contact page', max_length=150),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_hours',
            field=models.CharField(default='Mon - Sat: 9:00 AM - 7:00 PM', help_text='Phone availability hours', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='store_btn_text',
            field=models.CharField(default='Get Directions', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='store_btn_url',
            field=models.CharField(blank=True, default='https://maps.google.com/?q=Rangam+Saradha+Silks+Dharmavaram', help_text='Map URL or direction link', max_length=300),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='store_card_title',
            field=models.CharField(default='Visit Our Store', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_secondary',
            field=models.CharField(blank=True, default='Sun: 9:00 AM - 12:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(default='Door No-28-747-1, Rajendra Nagar, Dharmavaram, Sri Sathya Sai District, Andhra Pradesh - 515671'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='rangamsaradhasilks@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='+91 91002 88963', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='working_hours',
            field=models.CharField(default='Mon - Sat: 9:00 AM - 7:00 PM', max_length=100),
        ),
    ]
