# Generated by Django 5.2.16 on 2026-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage in Website Settings (e.g., 5.00 for 5% GST, or 0.00 for no tax). Applied to all products when set.', max_digits=5),
        ),
    ]
