# Generated by Django 5.2.16 on 2026-09-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_websitesetting_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='priority_sku_prefixes',
            field=models.CharField(blank=True, default='', help_text='Comma-separated SKU prefixes (e.g. RSS-GB, KJM-SUB) to control product display order on the shop page. Matching is prefix-based (e.g. RSS-GB matches RSS-GB-006).', max_length=500, verbose_name='Priority SKU Prefixes'),
        ),
    ]
