# Generated by Django 5.2.16 on 2026-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_websitesetting_priority_sku_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='artisan_weaving_image',
            field=models.ImageField(blank=True, help_text="Upload custom image for 'Ancient Weaving Art - Crafted by Hands That Breathe Tradition' section.", null=True, upload_to='editorial/', verbose_name='Ancient Weaving Art Artisan Image'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='brand_story_image',
            field=models.ImageField(blank=True, help_text="Upload custom image for the Brand Story ('Tradition Woven With Elegance / 40+ Years Legacy') section.", null=True, upload_to='editorial/', verbose_name='Brand Story Heritage Image'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='bridal_spotlight_image',
            field=models.ImageField(blank=True, help_text="Upload custom image for 'The Bridal Repertory - A Symphony of Pure Silk & Golden Zari' section.", null=True, upload_to='editorial/', verbose_name='Bridal Repertory Spotlight Image'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_1_image',
            field=models.ImageField(blank=True, help_text='Upload custom image for Kanchipuram Silks card. Defaults to curated static image if left blank.', null=True, upload_to='editorial/', verbose_name='Card 1 Image: Kanchipuram Silks'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_2_image',
            field=models.ImageField(blank=True, help_text='Upload custom image for Banarasi Brocades card. Defaults to curated static image if left blank.', null=True, upload_to='editorial/', verbose_name='Card 2 Image: Banarasi Brocades'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_3_image',
            field=models.ImageField(blank=True, help_text='Upload custom image for Bridal Masterpieces card. Defaults to curated static image if left blank.', null=True, upload_to='editorial/', verbose_name='Card 3 Image: Bridal Masterpieces'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='mosaic_festive_image',
            field=models.ImageField(blank=True, help_text="Upload custom image for the top right frame 'Festive Drapery Collections'.", null=True, upload_to='editorial/', verbose_name='Mosaic Top Right Image (Festive Drapery)'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='mosaic_handloom_image',
            field=models.ImageField(blank=True, help_text="Upload custom image for the bottom right frame 'Dharmavaram Hallmarks'.", null=True, upload_to='editorial/', verbose_name='Mosaic Bottom Right Image (Dharmavaram Hallmarks)'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='mosaic_hero_image',
            field=models.ImageField(blank=True, help_text="Upload custom image for the large left frame in 'Latest Weaves & Editorial Inspiration'.", null=True, upload_to='editorial/', verbose_name='Mosaic Large Focal Image (Heirloom Zari Artistry)'),
        ),
    ]
