# Generated by Django 5.2.16 on 2026-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_websitesetting_artisan_weaving_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_1_button_text',
            field=models.CharField(default='Explore Collection', max_length=50, verbose_name='Card 1 Button Text'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_1_button_url',
            field=models.CharField(default='/shop/category/kanchipuram-sarees/', help_text='Page URL or category link (e.g. /shop/category/kanchipuram-sarees/)', max_length=255, verbose_name='Card 1 Button Link (URL)'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_1_desc',
            field=models.TextField(default='Woven with authentic gold zari and sacred temple architecture borders for grand celebrations.', verbose_name='Card 1 Description'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_1_tag',
            field=models.CharField(default='ROYAL HERITAGE', max_length=100, verbose_name='Card 1 Tag / Subtitle'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_1_title',
            field=models.CharField(default='Kanchipuram Silks', max_length=150, verbose_name='Card 1 Title / Name'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_2_button_text',
            field=models.CharField(default='Explore Collection', max_length=50, verbose_name='Card 2 Button Text'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_2_button_url',
            field=models.CharField(default='/shop/category/banarasi-sarees/', help_text='Page URL or category link (e.g. /shop/category/banarasi-sarees/)', max_length=255, verbose_name='Card 2 Button Link (URL)'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_2_desc',
            field=models.TextField(default='Intricate floral jaal, meenakari embellishments, and cascading silk pallus for regal occasions.', verbose_name='Card 2 Description'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_2_tag',
            field=models.CharField(default='MUGHAL SPLENDOR', max_length=100, verbose_name='Card 2 Tag / Subtitle'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_2_title',
            field=models.CharField(default='Banarasi Brocades', max_length=150, verbose_name='Card 2 Title / Name'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_3_button_text',
            field=models.CharField(default='Explore Collection', max_length=50, verbose_name='Card 3 Button Text'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_3_button_url',
            field=models.CharField(default='/shop/category/bridal-collection/', help_text='Page URL or category link (e.g. /shop/category/bridal-collection/)', max_length=255, verbose_name='Card 3 Button Link (URL)'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_3_desc',
            field=models.TextField(default='Our hallmark bridal drapes infused with enduring warmth, double-warp silk, and artisanal soul.', verbose_name='Card 3 Description'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_3_tag',
            field=models.CharField(default='MASTER WEAVES', max_length=100, verbose_name='Card 3 Tag / Subtitle'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='collection_card_3_title',
            field=models.CharField(default='Bridal Masterpieces', max_length=150, verbose_name='Card 3 Title / Name'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='collection_card_1_image',
            field=models.ImageField(blank=True, help_text='Upload custom image for Card 1. Defaults to curated static image if left blank.', null=True, upload_to='editorial/', verbose_name='Card 1 Image'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='collection_card_2_image',
            field=models.ImageField(blank=True, help_text='Upload custom image for Card 2. Defaults to curated static image if left blank.', null=True, upload_to='editorial/', verbose_name='Card 2 Image'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='collection_card_3_image',
            field=models.ImageField(blank=True, help_text='Upload custom image for Card 3. Defaults to curated static image if left blank.', null=True, upload_to='editorial/', verbose_name='Card 3 Image'),
        ),
    ]
