# Generated by Django 5.2.16 on 2026-09-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_websitesetting_collection_card_1_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional mobile-optimized image (shown on phones & mobile screens). If not uploaded, desktop image will be used.', null=True, upload_to='offers/mobile/'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='image',
            field=models.ImageField(help_text='Desktop banner image', upload_to='offers/'),
        ),
    ]
