# Generated by Django 5.2.16 on 2026-09-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_offerbanner_mobile_image_alter_offerbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='tablet_image',
            field=models.ImageField(blank=True, help_text='Optional tablet-optimized image (768px - 991px)', null=True, upload_to='slider_tablet/'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='tablet_image',
            field=models.ImageField(blank=True, help_text='Optional tablet-optimized image (shown on iPads & tablet screens: 768px - 991px). If not uploaded, desktop image will be used.', null=True, upload_to='offers/tablet/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional mobile-optimized image (up to 767px)', null=True, upload_to='slider_mobile/'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='image',
            field=models.ImageField(help_text='Desktop banner image (wide screens)', upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional mobile-optimized image (shown on phones & mobile screens: up to 767px). If not uploaded, desktop image will be used.', null=True, upload_to='offers/mobile/'),
        ),
    ]
