# Generated by Django 5.2.16 on 2026-10-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_heroslider_tablet_image_offerbanner_tablet_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='cod_charge',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='cod_max_limit',
        ),
    ]
