# Generated by Django 5.2.16 on 2026-10-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_websitesetting_cod_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='priority_sku_prefixes',
            field=models.CharField(blank=True, default='', help_text='Enter any comma-separated SKU prefixes (e.g. RSS-SA, KJM-SUB, RSS-GB, or any new SKU code you create). Products matching any prefix you enter will automatically appear first on the shop page and homepage in this exact priority order.', max_length=500, verbose_name='Priority SKU Prefixes'),
        ),
    ]
