# Generated by Django 5.2.16 on 2026-10-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_websitesetting_priority_sku_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='new_arrivals_sku_prefix',
            field=models.CharField(blank=True, default='', help_text='Select a SKU prefix for the Curated Silk Masterpieces / New Arrivals section (e.g. RSS-GB). Products starting with this prefix will appear in New Arrivals.', max_length=100, verbose_name='New Arrivals SKU Prefix'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='todays_deals_sku_prefix',
            field=models.CharField(blank=True, default='', help_text="Select a SKU prefix for the Today's Deals homepage section (e.g. RSS-SA). Products starting with this prefix will appear in Today's Deals.", max_length=100, verbose_name="Today's Deals SKU Prefix"),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='priority_sku_prefixes',
            field=models.CharField(blank=True, default='', help_text='Legacy manual SKU prefixes.', max_length=500, verbose_name='Priority SKU Prefixes (Legacy)'),
        ),
    ]
