# Generated by Django 5.2.16 on 2026-10-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_websitesetting_new_arrivals_sku_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_1_button_text',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_1_button_url',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_1_desc',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_1_image',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_1_tag',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_1_title',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_2_button_text',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_2_button_url',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_2_desc',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_2_image',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_2_tag',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_2_title',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_3_button_text',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_3_button_url',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_3_desc',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_3_image',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_3_tag',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='collection_card_3_title',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='mosaic_festive_image',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='mosaic_handloom_image',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='mosaic_hero_image',
        ),
    ]
