# Generated by Django 5.2.16 on 2026-09-08 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_callslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbooking',
            name='saree_preference',
            field=models.CharField(blank=True, help_text='Saree or product of interest from general booking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callbooking',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='callbooking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_bookings', to='shop.product'),
        ),
    ]
