# Generated by Django 5.2.16 on 2026-09-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbooking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
    ]
