# Generated by Django 5.2.16 on 2026-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_callbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_number',
            field=models.CharField(blank=True, help_text='Customer or Business GSTIN for billing invoice', max_length=20, null=True, verbose_name='Billing GST Number / GSTIN'),
        ),
    ]
