# Generated by Django 5.2.16 on 2026-09-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_link',
            field=models.URLField(blank=True, help_text='Direct URL to track the courier shipment', max_length=500, null=True, verbose_name='Tracking Link'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Consignment number or AWB number', max_length=100, null=True, verbose_name='Tracking / AWB Number'),
        ),
    ]
