# Generated by Django 5.2.16 on 2026-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_tracking_link_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbooking',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Consultation fee in INR', max_digits=8),
        ),
        migrations.AddField(
            model_name='callbooking',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI / QR Code'), ('CARD', 'Credit / Debit Card'), ('NETBANKING', 'Net Banking'), ('ONLINE', 'Online Payment')], default='UPI', max_length=30),
        ),
        migrations.AddField(
            model_name='callbooking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction or UPI reference ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20),
        ),
    ]
