# Generated by Django 5.2.16 on 2026-09-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_paid_at_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
