# Generated by Django 5.2.16 on 2026-09-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_collection_delete_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authenticity',
            field=models.CharField(blank=True, default='Silk Mark Certified 100% Handcrafted Mulberry Silk', help_text='Certification / Authenticity (e.g., Silk Mark Certified)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='saree_length',
            field=models.CharField(blank=True, default='5.5 Meters (Approx.) + 0.8 Meter Running Blouse', help_text='Length specification (e.g., 5.5 Meters + 0.8 Meter Running Blouse)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='zari_type',
            field=models.CharField(blank=True, default='Premium Gold Zari Traditional Weave', help_text='Zari specification (e.g., Premium Gold Zari Traditional Weave)', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='', help_text="Additional specifications in plain text (enter one per line, e.g., 'Blouse: Contrast Brocade' or 'Border: Temple Border')"),
        ),
    ]
