# Generated by Django 5.2.16 on 2026-09-22 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_authenticity_product_saree_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='apply_to',
            field=models.CharField(choices=[('ALL', 'All Products'), ('CATEGORIES', 'Specific Categories'), ('PRODUCTS', 'Specific Products')], default='ALL', help_text='Choose where this coupon can be applied', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories eligible for this coupon', related_name='coupons', to='shop.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products eligible for this coupon', related_name='coupons', to='shop.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Start date from which this coupon becomes valid', null=True),
        ),
    ]
