# Generated by Django 5.2.16 on 2026-09-22 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_coupon_apply_to_coupon_categories_coupon_products_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkStockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=50)),
                ('stock', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bulk_stock/')),
                ('short_description', models.TextField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('fabric', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('material', models.CharField(blank=True, default='', max_length=100)),
                ('occasion', models.CharField(blank=True, default='', max_length=100)),
                ('zari_type', models.CharField(blank=True, default='Premium Gold Zari Traditional Weave', max_length=150)),
                ('saree_length', models.CharField(blank=True, default='5.5 Meters (Approx.) + 0.8 Meter Running Blouse', max_length=150)),
                ('authenticity', models.CharField(blank=True, default='Silk Mark Certified 100% Handcrafted Mulberry Silk', max_length=200)),
                ('specifications', models.TextField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=150)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_stock_products', to='shop.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_stock_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Stock',
                'verbose_name_plural': 'Bulk Stock',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BulkStockProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bulk_stock/')),
                ('display_order', models.IntegerField(default=0)),
                ('bulk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.bulkstockproduct')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
