# Generated by Django 5.2.16 on 2026-09-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_bulkstockproduct_bulkstockproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkstockproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bulkstockproduct',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkstockproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkstockproduct',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkstockproduct',
            name='is_today_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkstockproduct',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkstockproduct',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bulkstockproduct',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
