# Generated by Django 5.2.16 on 2026-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_bulkstockproduct_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_time',
            field=models.TimeField(blank=True, help_text='Expiry time (optional, defaults to 23:59:59)', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time (optional, defaults to 00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(help_text='Expiry date on which this coupon expires'),
        ),
    ]
