# Generated by Django 5.2.16 on 2026-10-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_coupon_expiry_time_coupon_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment (Razorpay)'), ('RAZORPAY', 'Pay Online (Razorpay)'), ('OFFLINE', 'Offline Store'), ('COD', 'Cash On Delivery (Disabled)')], default='ONLINE', max_length=20),
        ),
    ]
