# Generated by Django 5.2.16 on 2026-10-01 09:58

from django.db import migrations, models


def clean_hardcoded_defaults(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    BulkStockProduct = apps.get_model('shop', 'BulkStockProduct')

    Product.objects.filter(zari_type="Premium Gold Zari Traditional Weave").update(zari_type="")
    Product.objects.filter(saree_length="5.5 Meters (Approx.) + 0.8 Meter Running Blouse").update(saree_length="")
    Product.objects.filter(authenticity="Silk Mark Certified 100% Handcrafted Mulberry Silk").update(authenticity="")

    BulkStockProduct.objects.filter(zari_type="Premium Gold Zari Traditional Weave").update(zari_type="")
    BulkStockProduct.objects.filter(saree_length="5.5 Meters (Approx.) + 0.8 Meter Running Blouse").update(saree_length="")
    BulkStockProduct.objects.filter(authenticity="Silk Mark Certified 100% Handcrafted Mulberry Silk").update(authenticity="")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkstockproduct',
            name='authenticity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bulkstockproduct',
            name='saree_length',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bulkstockproduct',
            name='zari_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='authenticity',
            field=models.CharField(blank=True, default='', help_text='Certification / Authenticity (e.g., Silk Mark Certified)', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='saree_length',
            field=models.CharField(blank=True, default='', help_text='Length specification (e.g., 5.5 Meters + 0.8 Meter Running Blouse)', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='zari_type',
            field=models.CharField(blank=True, default='', help_text='Zari specification (e.g., Premium Gold Zari Traditional Weave)', max_length=150),
        ),
        migrations.RunPython(clean_hardcoded_defaults, reverse_code=migrations.RunPython.noop),
    ]
