# Generated by Django 5.2.16 on 2026-10-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_bulkstockproduct_authenticity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct video file upload (MP4, WebM, MOV)', max_length=500, null=True, upload_to='product_videos/'),
        ),
    ]
