# Generated by Django 5.2.16 on 2026-10-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_product_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceChange',
            fields=[
            ],
            options={
                'verbose_name': 'Product Price Change',
                'verbose_name_plural': 'Product Price Change',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
    ]
